# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true
  AllowBeforeTrailingComments: true
  ForceEqualSignAlignment: true

Layout/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true

# Hash alignment configuration for RuboCop
Layout/HashAlignment:
  # Align hash values in columns
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
